### PR TITLE
added RouteDescription tests

### PR DESCRIPTION
**Pull request by fscgolden**
Co-authored-by: Chris LeBrett <100822842+fscgolden@users.noreply.github.com>
Co-authored-by: Robby Tipton <100332566+RobbyTipton@users.noreply.github.com>
Co-authored-by: Joseph Park <10874783+joeepark@users.noreply.github.com>
Co-authored-by: David Kim <101825171+codejunkie7@users.noreply.github.com>
Co-authored-by: Kevin HoEun Lee <14950124+khobread@users.noreply.github.com>

### CODE REVIEW

**Review by khobread — APPROVED** [review]
Good unit tests. Thank you Chris!!

**Review by codejunkie7 — APPROVED** [review]
Looks like a good test file Chris.

**Review by joeepark — APPROVED** [review]
Nice tests Chris!

**Review by RobbyTipton — APPROVED** [review]
Looks good. Glad to have test coverage for our new component.

**Pull request merged**
