### PR TITLE
Merging latest beta features that enhance overall visualizations and user experience

### PR DESCRIPTION
**Pull request by Theqwertypusher**
### **Description**
The latest beta features focused on improving data visualizations and overall user experience by introducing new functionality for visualized components and converting previous D3 visualizations to VISX. 

### **Changes made**
1. Expanded compatibility with Recoil’s newest update (0.0.13)
2. Added visualization for atom/selectors/component mapping
3. Improved history tab by contextualizing snapshots with a dynamic legend
4. Re-envisioned the component map by incorporating a brand new visualization        
    D3/React library called VISX to provide users with more robust views
5. Revamped the performance tab to better visualize component rendering trends and 
    potential performance bottleneck as state changes
6. Giving visualized components onHover functionality that highlights corresponding 
    DOM elements
7. Overall general enhancements to the codebase (improving modularity, reducing 
   technical debt, and enhancing onboarding)

react-calculator-demo

recoil-todo-demo

### CODE REVIEW

**Review by VNguyenCode — APPROVED** [review]
This looks great - we made great improvements to the visual interfaces, Recoil compatibility in the other sections look good, and the onHover feature will provide enhanced interactivity for our users with the application.

**Review by SanjayLavingia — APPROVED** [review]
Great job! Really appreciate everyone's hard work with all the features!

**Review by guizzettic — APPROVED** [review]
Awesome work team. Great job reducing technical debt, improving the performance of the applicatoin, as well as updating the visualization of the app.

**Review by AlexanderLanderos — APPROVED** [review]
Excellent work team

**Pull request merged**
